# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodercli < Formula
  desc "Qoder AI CLI tool"
  homepage "https://qoder.com"
  version "0.0.10"
  license "Commercial"

  on_macos do
    if Hardware::CPU.intel?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.10/qodercli_0.0.10_darwin_amd64.tar.gz"
      sha256 "1ab9ff9cd83ceab17e8d655eed444ee0d23f1cf8cbef4cdc8d20c024d9cbaf22"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.10/qodercli_0.0.10_darwin_arm64.tar.gz"
      sha256 "6b0f70623fd3f4b6a77ecab5c66897be3125212cca937efafdba1e8c09d2f7df"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.10/qodercli_0.0.10_linux_amd64.tar.gz"
      sha256 "a441d999193584f29e5610aa6dd883c768fe7ee98e33ef99e3b8f26d965803ff"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.10/qodercli_0.0.10_linux_arm64.tar.gz"
      sha256 "c1d8d475453bf1879608fe0039e2f40c893f01c6db88c0f4865f965b37f04f32"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  test do
    system "#{bin}/qodercli", "--version"
  end
end
