# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodercli < Formula
  desc "Qoder AI CLI tool"
  homepage "https://qoder.com"
  version "0.0.11"
  license "Commercial"

  on_macos do
    if Hardware::CPU.intel?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.11/qodercli_0.0.11_darwin_amd64.tar.gz"
      sha256 "c2984428e461af8532f60cc3e4c0c29366d49b7b5ca9550b60f9717d642a261b"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.11/qodercli_0.0.11_darwin_arm64.tar.gz"
      sha256 "e9eb0f11716640b163440a7b4935c87b80a1952084b22e72b32b84c11892a160"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.11/qodercli_0.0.11_linux_amd64.tar.gz"
      sha256 "8b9c47a68bc211b92d52dcdafe5d5fce86b6e169e3dbd5a474d142dd77e8b6fd"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.11/qodercli_0.0.11_linux_arm64.tar.gz"
      sha256 "ce56359fe7ff6cfa34de69c1e6bf833309908697e470f8d0e3e8c508098af86a"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  test do
    system "#{bin}/qodercli", "--version"
  end
end
