# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodercli < Formula
  desc "Qoder AI CLI tool"
  homepage "https://qoder.com"
  version "0.0.16"
  license "Commercial"

  on_macos do
    if Hardware::CPU.intel?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.16/qodercli_0.0.16_darwin_amd64.tar.gz"
      sha256 "7372929662f788b663bc4e3862cc013016ecf9ed04f03e3dc0331199950bac4f"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.16/qodercli_0.0.16_darwin_arm64.tar.gz"
      sha256 "46fa39ea6d6b0d33c36817582ad0adb342bd7ced69c3c94841736351d91fa0a4"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.16/qodercli_0.0.16_linux_amd64.tar.gz"
      sha256 "9730387884b141136c72abedb50d5cc3f7cd4b1940b8eba1de124a32301cc401"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/v0.0.16/qodercli_0.0.16_linux_arm64.tar.gz"
      sha256 "042d3c78b81951d1a81b28c0527e312276c1ec03e810de2b46a22887e7ee4577"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  test do
    system "#{bin}/qodercli", "--version"
  end
end
