# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodercli < Formula
  desc "Qoder AI CLI tool"
  homepage "https://qoder.com"
  version "0.0.10-alpha2"
  license "Commercial"

  on_macos do
    if Hardware::CPU.intel?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha2/qodercli_0.0.10-alpha2_darwin_amd64.zip"
      sha256 "2277cc273686133ac1704e8b96cafdd638c6c9a62ced894896c34ccc961eb80c"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha2/qodercli_0.0.10-alpha2_darwin_arm64.zip"
      sha256 "0e61606692589133b6ed799a168fc94731021f1882a1112a81e2f5e8d34341c8"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha2/qodercli_0.0.10-alpha2_linux_amd64.tar.gz"
      sha256 "807efe80a9c1213cc17141b361f4c7985de9e073a26e85fe6b92d3052701f654"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha2/qodercli_0.0.10-alpha2_linux_arm64.tar.gz"
      sha256 "df5ca7bc94f8d7fd1afb8f80eff534a9b9c8dec178737bb31d8f43e7629df72c"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  test do
    system "#{bin}/qodercli", "--version"
  end
end
