# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodercli < Formula
  desc "Qoder AI CLI tool"
  homepage "https://qoder.com"
  version "0.0.10-alpha3"
  license "Commercial"

  on_macos do
    if Hardware::CPU.intel?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha3/qodercli_0.0.10-alpha3_darwin_amd64.zip"
      sha256 "1b96c87f28392150b78ac51fd0b949fc4e47861bb3e6dd7fe73d782c9e8dc697"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha3/qodercli_0.0.10-alpha3_darwin_arm64.zip"
      sha256 "1ffddba0a84a9950fe4419667d73807c95ca32597f3bf5feb95b3ef05dc9ee93"

      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha3/qodercli_0.0.10-alpha3_linux_amd64.tar.gz"
      sha256 "b20e6a50f2ceb8e3d86973584ccfb58d49ba6242a563645367f63f62a44c0caf"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://qs-cli-dev.oss-cn-hangzhou.aliyuncs.com/qodercli/releases/0.0.10-alpha3/qodercli_0.0.10-alpha3_linux_arm64.tar.gz"
      sha256 "f93f6eb56135cea6ca21489fa542bd381f8ac36408d36ba002a59dd1c4aff789"
      def install
        bin.install "qodercli"
        (bin/".qodercli-install-resource").write "homebrew"
      end
    end
  end

  test do
    system "#{bin}/qodercli", "--version"
  end
end
